# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

#triangle_numbers aan lijstje toevoegen
#delers van triangleno in triangle_numbers > 500

#Duurt nog veel te lang!!!!!! moet worden geoptimaliseerd

import sys
n = 90000
j = 0
delers = 0

triangle_numbers = []

for i in range(1,n):
    j += i
    triangle_numbers.append(j)


for number in triangle_numbers: 
    delers = 0
    for x in range(1,number+1):
        if number % x == 0:
            delers += 1        
            if 502 > delers > 498:
                print(number)
                sys.exit(0)
    print(number, delers)
